export const database = [
    { email: "LiamCarter@abceez.com", firstName: "Liam", lastName: 'Carter', role: "admin", status: "active", phone: "555-0201", id: "ID005", createdAt: "2024-12-02", profilePicture: "https://randomuser.me/api/portraits/men/5.jpg" },
    { email: "EmmaDavis@abceez.com", firstName: "Emma", lastName: 'Davis', role: "js-deve", status: "active", phone: "555-0202", id: "ID006", createdAt: "2023-08-15", profilePicture: "https://randomuser.me/api/portraits/women/6.jpg" },
    { email: "NoahEvans@abceez.com", firstName: "Noah", lastName: 'Evans', role: "cust-supp", status: "inactive", phone: "555-0203", id: "ID007", createdAt: "2022-11-23", profilePicture: "https://randomuser.me/api/portraits/men/7.jpg" },
    { email: "OliviaGarcia@abceez.com", firstName: "Olivia", lastName: 'Garcia', role: "oper-mana", status: "active", phone: "555-0204", id: "ID008", createdAt: "2025-02-05", profilePicture: "https://randomuser.me/api/portraits/women/8.jpg" },
    { email: "AvaLee@abceez.com", firstName: "Ava", lastName: 'Lee', role: "js-deve", status: "active", phone: "555-0206", id: "ID010", createdAt: "2023-04-09", profilePicture: "https://randomuser.me/api/portraits/women/10.jpg" },
    { email: "LoganMartin@abceez.com", firstName: "Logan", lastName: 'Martin', role: "cust-supp", status: "inactive", phone: "555-0207", id: "ID011", createdAt: "2021-12-30", profilePicture: "https://randomuser.me/api/portraits/men/11.jpg" },
    { email: "SophiaNelson@abceez.com", firstName: "Sophia", lastName: 'Nelson', role: "oper-mana", status: "active", phone: "555-0208", id: "ID012", createdAt: "2024-10-12", profilePicture: "https://randomuser.me/api/portraits/women/12.jpg" },
    { email: "IsabellaRamirez@abceez.com", firstName: "Isabella", lastName: 'Ramirez', role: "js-deve", status: "active", phone: "555-0210", id: "ID014", createdAt: "2022-07-01", profilePicture: "https://randomuser.me/api/portraits/women/14.jpg" },
    { email: "LucasScott@abceez.com", firstName: "Lucas", lastName: 'Scott', role: "supr-admin", status: "inactive", phone: "555-0211", id: "ID015", createdAt: "2023-09-08", profilePicture: "https://randomuser.me/api/portraits/men/15.jpg" },
    { email: "MiaTaylor@abceez.com", firstName: "Mia", lastName: 'Taylor', role: "oper-mana", status: "active", phone: "555-0212", id: "ID016", createdAt: "2024-01-18", profilePicture: "https://randomuser.me/api/portraits/women/16.jpg" },
    { email: "EthanWalker@abceez.com", firstName: "Ethan", lastName: 'Walker', role: "admin", status: "active", phone: "555-0213", id: "ID017", createdAt: "2023-06-11", profilePicture: "https://randomuser.me/api/portraits/men/17.jpg" },
    { email: "JamesAnderson@abceez.com", firstName: "James", lastName: 'Anderson', role: "cust-supp", status: "active", phone: "555-0215", id: "ID019", createdAt: "2022-08-19", profilePicture: "https://randomuser.me/api/portraits/men/19.jpg" },
    { email: "CharlotteHernandez@abceez.com", firstName: "Charlotte", lastName: 'Hernandez', role: "oper-mana", status: "inactive", phone: "555-0216", id: "ID020", createdAt: "2023-10-05", profilePicture: "https://randomuser.me/api/portraits/women/20.jpg" },
    { email: "BenjaminMoore@abceez.com", firstName: "Benjamin", lastName: 'Moore', role: "supr-admin", status: "active", phone: "555-0217", id: "ID021", createdAt: "2024-03-12", profilePicture: "https://randomuser.me/api/portraits/men/21.jpg" },
    { email: "HarperMartinez@abceez.com", firstName: "Harper", lastName: 'Martinez', role: "js-deve", status: "active", phone: "555-0218", id: "ID022", createdAt: "2024-07-22", profilePicture: "https://randomuser.me/api/portraits/women/22.jpg" },
    { email: "EvelynClark@abceez.com", firstName: "Evelyn", lastName: 'Clark', role: "oper-mana", status: "active", phone: "555-0220", id: "ID024", createdAt: "2022-09-14", profilePicture: "https://randomuser.me/api/portraits/women/24.jpg" }
];